version: '3'
services:
    web:
        build: .
        ports:
            - 8000:8000
        environment:
            - FLASK_APP=app.py
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=fyyur
            - DB_USER=postgres
            - DB_PASSWORD=artists
        # env_file:
        #     - env.list
        depends_on:
            - db
    db:
        image: postgres:11-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=artists
            - POSTGRES_DB=fyyur
#         volumes:
#             - flask_artist_booking_data:/var/lib/postgresql/data

# volumes:
#     flask_artist_booking_data: